Repository sequentech/strand, pull requests merged in 2022-07, with the labels that each got.

#27 Add github actions
  .github/dependabot.yml
  .github/workflows/ci.yml
  .gitignore
  .reuse/dep5
  Cargo.lock.license
  Cargo.toml
  LICENSES/AGPL-3.0-only.txt
  README.md
  benches/README.md
  benches/encrypt.rs
  benches/shuffle.rs
  deny.toml
  flake.lock
  flake.lock.license
  flake.nix
  src/backend.rs
  src/backend/num_bigint.rs
  src/backend/ristretto.rs
  src/backend/rug.rs
  src/byte_tree.rs
  src/context.rs
  src/keymaker.rs
  src/lib.rs
  src/rnd.rs
  src/symmetric.rs
  src/threshold.rs
  src/util.rs
  src/wasm.rs
  src/wasm/test.rs
  src/wasm/test/README.md
  src/wasm/test/bench.rs
  src/wasm/test/example.js
  src/wasm/test/example.rs
  src/wasm/test/fd.js.license
  src/wasm/test/serve.py
  src/wasm/test/test.html
  src/wasm/test/test.rs
  src/wasm/test/test_noworker.html
  src/wasm/test/worker.js
  src/wasm/test/worker_t.js
  src/zkp.rs
Labels: enhancement

#30 Fix slack badge in README.md
  README.md
Labels: documentation

#32 README: Fix codecov&CI badges and move links to bottom
  README.md
Labels: documentation

#33 Fixing benchmark gh actions
  .github/workflows/ci.yml
  Cargo.toml
  flake.nix
Labels: infrastructure

#36 making bots less verbose
  .github/workflows/ci.yml
  codecov.yml
Labels: infrastructure

#35 Nix build for wasm
  .gitignore
  Cargo.lock.copy
  Cargo.lock.copy.license
  Cargo.toml
  README.md
  flake.lock
  flake.nix
Labels: infrastructure

#43 cachix: changing the binary cache to sequent's organization
  .github/workflows/ci.yml
Labels: infrastructure

#44 Flake lock
  .github/workflows/update-flake.yml
Labels: enhancement, infrastructure

#47 Browserstack tests
  .github/workflows/ci.yml
  README.md
  browserstack/.gitignore
  browserstack/conf/base.conf.js
  browserstack/conf/local-test.conf.js
  browserstack/conf/test.conf.js
  browserstack/package-lock.json
  browserstack/package-lock.json.license
  browserstack/package.json
  browserstack/package.json.license
  browserstack/tests/specs/local_test.js
  browserstack/tests/specs/test.js
Labels: enhancement

#48 Multiple targets on nix flakes
  README.md
  flake.nix
Labels: enhancement

#50 update wasm-bindgen
  Cargo.lock.copy
  Cargo.toml
  deny.toml
  flake.lock
  flake.nix
Labels: dependencies

#51 Add Github Dev Containers
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/devcontainer.json.license
  .devcontainer/etc/bash.bashrc
  .devcontainer/etc/devcontainer.sh
  .devcontainer/etc/devcontainer.sh.license
  .devcontainer/etc/direnv.toml
  .devcontainer/etc/envrc
  .devcontainer/etc/nix.conf
  .envrc
  .github/workflows/ci.yml
  .gitignore
  LICENSES/MIT.txt
  README.md
  flake.lock
  flake.nix
Labels: enhancement
